# Generated by Django 3.0.6 on 2020-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_vehicle', models.CharField(choices=[('CAR', 'Car'), ('MOT', 'Motorbike'), ('TRU', 'Truck'), ('ATV', 'ATV/Quad'), ('TRA', 'Trailer'), ('OTH', 'Other')], default='CAR', max_length=3)),
                ('brand', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('license_plate', models.CharField(blank=True, default='XX-XX-XX', max_length=10, verbose_name='License Plate ')),
                ('identification', models.CharField(blank=True, default='', max_length=20, verbose_name='Identification/Serial number (VIN) ')),
                ('year', models.DateField(help_text='Enter the date of first registration of your vehicle or January first of the year of production if first registration date is unknown', verbose_name='Date of first registration (Production Year)')),
                ('date_of_purchase', models.DateField(verbose_name='Date of purchase')),
            ],
        ),
    ]
